// Generated by scripts/gen-types.py — do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  stash: {
    Tables: {
      spaces: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          kind: Database["stash"]["Enums"]["space_kind"];
          color_token: string;
          icon: string | null;
          due_date: string | null;
          sort_order: number;
          archived: boolean;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          name: string;
          kind?: Database["stash"]["Enums"]["space_kind"];
          color_token?: string;
          icon?: string | null;
          due_date?: string | null;
          sort_order?: number;
          archived?: boolean;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          kind?: Database["stash"]["Enums"]["space_kind"];
          color_token?: string;
          icon?: string | null;
          due_date?: string | null;
          sort_order?: number;
          archived?: boolean;
          description?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      saves: {
        Row: {
          id: string;
          user_id: string;
          client_id: string | null;
          source_url: string;
          platform: Database["stash"]["Enums"]["platform"];
          space_id: string | null;
          status: Database["stash"]["Enums"]["save_status"];
          video_path: string | null;
          thumb_path: string | null;
          duration_s: number | null;
          creator_handle: string | null;
          caption: string | null;
          saved_at: string;
          user_note: string | null;
          voice_note_path: string | null;
          created_at: string;
          updated_at: string;
          title: string | null;
          error: string | null;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          client_id?: string | null;
          source_url: string;
          platform: Database["stash"]["Enums"]["platform"];
          space_id?: string | null;
          status?: Database["stash"]["Enums"]["save_status"];
          video_path?: string | null;
          thumb_path?: string | null;
          duration_s?: number | null;
          creator_handle?: string | null;
          caption?: string | null;
          saved_at?: string;
          user_note?: string | null;
          voice_note_path?: string | null;
          created_at?: string;
          updated_at?: string;
          title?: string | null;
          error?: string | null;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          client_id?: string | null;
          source_url?: string;
          platform?: Database["stash"]["Enums"]["platform"];
          space_id?: string | null;
          status?: Database["stash"]["Enums"]["save_status"];
          video_path?: string | null;
          thumb_path?: string | null;
          duration_s?: number | null;
          creator_handle?: string | null;
          caption?: string | null;
          saved_at?: string;
          user_note?: string | null;
          voice_note_path?: string | null;
          created_at?: string;
          updated_at?: string;
          title?: string | null;
          error?: string | null;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      insights: {
        Row: {
          save_id: string;
          user_id: string;
          title: string | null;
          key_idea: string | null;
          takeaways: Json;
          actions: Json;
          intent: Database["stash"]["Enums"]["intent"] | null;
          tags: string[];
          language: string | null;
          suggested_space_id: string | null;
          confidence: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          save_id: string;
          user_id?: string;
          title?: string | null;
          key_idea?: string | null;
          takeaways?: Json;
          actions?: Json;
          intent?: Database["stash"]["Enums"]["intent"] | null;
          tags?: string[];
          language?: string | null;
          suggested_space_id?: string | null;
          confidence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          save_id?: string;
          user_id?: string;
          title?: string | null;
          key_idea?: string | null;
          takeaways?: Json;
          actions?: Json;
          intent?: Database["stash"]["Enums"]["intent"] | null;
          tags?: string[];
          language?: string | null;
          suggested_space_id?: string | null;
          confidence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      transcripts: {
        Row: {
          save_id: string;
          user_id: string;
          segments: Json;
          full_text: string;
          tsv: unknown | null;
          created_at: string;
        };
        Insert: {
          save_id: string;
          user_id?: string;
          segments?: Json;
          full_text?: string;
          created_at?: string;
        };
        Update: {
          save_id?: string;
          user_id?: string;
          segments?: Json;
          full_text?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      embeddings: {
        Row: {
          save_id: string;
          user_id: string;
          vector: string;
          model: string;
          created_at: string;
        };
        Insert: {
          save_id: string;
          user_id?: string;
          vector: string;
          model: string;
          created_at?: string;
        };
        Update: {
          save_id?: string;
          user_id?: string;
          vector?: string;
          model?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      places: {
        Row: {
          id: string;
          save_id: string;
          user_id: string;
          name: string;
          lat: number | null;
          lng: number | null;
          address: string | null;
          maps_place_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          save_id: string;
          user_id?: string;
          name: string;
          lat?: number | null;
          lng?: number | null;
          address?: string | null;
          maps_place_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          save_id?: string;
          user_id?: string;
          name?: string;
          lat?: number | null;
          lng?: number | null;
          address?: string | null;
          maps_place_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      states: {
        Row: {
          save_id: string;
          user_id: string;
          watched_at: string | null;
          kept: boolean;
          archived_at: string | null;
          applied_at: string | null;
          skip_count: number;
          last_shown_at: string | null;
          created_at: string;
        };
        Insert: {
          save_id: string;
          user_id?: string;
          watched_at?: string | null;
          kept?: boolean;
          archived_at?: string | null;
          applied_at?: string | null;
          skip_count?: number;
          last_shown_at?: string | null;
          created_at?: string;
        };
        Update: {
          save_id?: string;
          user_id?: string;
          watched_at?: string | null;
          kept?: boolean;
          archived_at?: string | null;
          applied_at?: string | null;
          skip_count?: number;
          last_shown_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      cards: {
        Row: {
          id: string;
          save_id: string;
          user_id: string;
          prompt: string;
          answer: string;
          ease: number;
          interval_days: number;
          repetitions: number;
          due_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          save_id: string;
          user_id?: string;
          prompt: string;
          answer: string;
          ease?: number;
          interval_days?: number;
          repetitions?: number;
          due_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          save_id?: string;
          user_id?: string;
          prompt?: string;
          answer?: string;
          ease?: number;
          interval_days?: number;
          repetitions?: number;
          due_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      reviews: {
        Row: {
          id: string;
          card_id: string;
          user_id: string;
          answered_at: string;
          grade: number | null;
          voice_answer_text: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          card_id: string;
          user_id?: string;
          answered_at?: string;
          grade?: number | null;
          voice_answer_text?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          card_id?: string;
          user_id?: string;
          answered_at?: string;
          grade?: number | null;
          voice_answer_text?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      syntheses: {
        Row: {
          id: string;
          space_id: string | null;
          user_id: string;
          topic: string | null;
          points: Json;
          disagreements: Json;
          suggested_action: string | null;
          source_save_ids: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          space_id?: string | null;
          user_id?: string;
          topic?: string | null;
          points?: Json;
          disagreements?: Json;
          suggested_action?: string | null;
          source_save_ids?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          space_id?: string | null;
          user_id?: string;
          topic?: string | null;
          points?: Json;
          disagreements?: Json;
          suggested_action?: string | null;
          source_save_ids?: string[];
          created_at?: string;
        };
        Relationships: [];
      };
      reminders: {
        Row: {
          id: string;
          save_id: string;
          user_id: string;
          kind: Database["stash"]["Enums"]["reminder_kind"];
          fire_at: string | null;
          geofence: Json | null;
          fired: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          save_id: string;
          user_id?: string;
          kind: Database["stash"]["Enums"]["reminder_kind"];
          fire_at?: string | null;
          geofence?: Json | null;
          fired?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          save_id?: string;
          user_id?: string;
          kind?: Database["stash"]["Enums"]["reminder_kind"];
          fire_at?: string | null;
          geofence?: Json | null;
          fired?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      jobs: {
        Row: {
          id: string;
          save_id: string | null;
          space_id: string | null;
          user_id: string;
          type: Database["stash"]["Enums"]["job_type"];
          state: Database["stash"]["Enums"]["job_state"];
          attempts: number;
          error: string | null;
          locked_at: string | null;
          run_after: string;
          payload: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          save_id?: string | null;
          space_id?: string | null;
          user_id?: string;
          type: Database["stash"]["Enums"]["job_type"];
          state?: Database["stash"]["Enums"]["job_state"];
          attempts?: number;
          error?: string | null;
          locked_at?: string | null;
          run_after?: string;
          payload?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          save_id?: string | null;
          space_id?: string | null;
          user_id?: string;
          type?: Database["stash"]["Enums"]["job_type"];
          state?: Database["stash"]["Enums"]["job_state"];
          attempts?: number;
          error?: string | null;
          locked_at?: string | null;
          run_after?: string;
          payload?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      exports: {
        Row: {
          id: string;
          space_id: string;
          user_id: string;
          kind: Database["stash"]["Enums"]["export_kind"];
          options: Json;
          file_path: string | null;
          share_slug: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          space_id: string;
          user_id?: string;
          kind: Database["stash"]["Enums"]["export_kind"];
          options?: Json;
          file_path?: string | null;
          share_slug?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          space_id?: string;
          user_id?: string;
          kind?: Database["stash"]["Enums"]["export_kind"];
          options?: Json;
          file_path?: string | null;
          share_slug?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      usage: {
        Row: {
          id: string;
          user_id: string;
          save_id: string | null;
          kind: string;
          input_tokens: number;
          output_tokens: number;
          audio_seconds: number;
          usd: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          save_id?: string | null;
          kind: string;
          input_tokens?: number;
          output_tokens?: number;
          audio_seconds?: number;
          usd?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          save_id?: string | null;
          kind?: string;
          input_tokens?: number;
          output_tokens?: number;
          audio_seconds?: number;
          usd?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      settings: {
        Row: {
          user_id: string;
          theme: Database["stash"]["Enums"]["theme_pref"];
          accent: string;
          accent_custom: string | null;
          text_scale: number;
          density: number;
          reduce_motion: boolean;
          haptics: boolean;
          monthly_budget_usd: number;
          queue_time: string;
          queue_minutes: number;
          quiet_hours: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id?: string;
          theme?: Database["stash"]["Enums"]["theme_pref"];
          accent?: string;
          accent_custom?: string | null;
          text_scale?: number;
          density?: number;
          reduce_motion?: boolean;
          haptics?: boolean;
          monthly_budget_usd?: number;
          queue_time?: string;
          queue_minutes?: number;
          quiet_hours?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          theme?: Database["stash"]["Enums"]["theme_pref"];
          accent?: string;
          accent_custom?: string | null;
          text_scale?: number;
          density?: number;
          reduce_motion?: boolean;
          haptics?: boolean;
          monthly_budget_usd?: number;
          queue_time?: string;
          queue_minutes?: number;
          quiet_hours?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      search_saves: { Args: { p_query: string; p_space_id?: string | null; p_embedding?: string | null; p_limit?: number }; Returns: { save_id: string; score: number; snippet: string | null; snippet_start: number | null }[] };
      related_saves: { Args: { p_save_id: string; p_limit?: number }; Returns: { save_id: string; similarity: number }[] };
      request_reprocess: { Args: { p_save_id: string }; Returns: undefined };
    };
    Enums: {
      space_kind: "topic" | "project" | "inbox";
      platform: "instagram" | "tiktok" | "youtube" | "web" | "screenshot";
      save_status: "queued" | "processing" | "ready" | "failed" | "dead_link";
      intent: "learn" | "try" | "visit" | "buy" | "inspire" | "fun";
      reminder_kind: "time" | "place" | "context";
      job_type: "ingest" | "reprocess" | "synthesize" | "export";
      job_state: "queued" | "running" | "done" | "failed";
      export_kind: "brief" | "moodboard" | "deck" | "collection";
      theme_pref: "system" | "dark" | "light" | "black";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database["stash"]["Tables"]> = Database["stash"]["Tables"][T]["Row"];
export type Enums<T extends keyof Database["stash"]["Enums"]> = Database["stash"]["Enums"][T];
