#!/usr/bin/env python3
"""Writes lib/supabase/types.ts for the `stash` schema.

The Supabase type generator only covers `public` on this project, so the
column list is kept here (mirrors supabase/migrations). Format per column:
name:type[?=nullable][!=has default]. Re-run after a migration changes columns.
"""
TABLES = {
 "spaces": "id:uuid! user_id:uuid! name:text kind:space_kind! color_token:text! icon:text? due_date:date? sort_order:int! archived:bool! description:text? created_at:ts!",
 "saves": "id:uuid! user_id:uuid! client_id:uuid? source_url:text platform:platform space_id:uuid? status:save_status! video_path:text? thumb_path:text? duration_s:num? creator_handle:text? caption:text? saved_at:ts! user_note:text? voice_note_path:text? created_at:ts! updated_at:ts! title:text? error:text? processed_at:ts?",
 "insights": "save_id:uuid user_id:uuid! title:text? key_idea:text? takeaways:json! actions:json! intent:intent? tags:text[]! language:text? suggested_space_id:uuid? confidence:num? created_at:ts! updated_at:ts!",
 "transcripts": "save_id:uuid user_id:uuid! segments:json! full_text:text! tsv:unknown?! created_at:ts!",
 "embeddings": "save_id:uuid user_id:uuid! vector:text model:text created_at:ts!",
 "places": "id:uuid! save_id:uuid user_id:uuid! name:text lat:num? lng:num? address:text? maps_place_id:text? created_at:ts!",
 "states": "save_id:uuid user_id:uuid! watched_at:ts? kept:bool! archived_at:ts? applied_at:ts? skip_count:int! last_shown_at:ts? created_at:ts!",
 "cards": "id:uuid! save_id:uuid user_id:uuid! prompt:text answer:text ease:num! interval_days:int! repetitions:int! due_at:ts! created_at:ts!",
 "reviews": "id:uuid! card_id:uuid user_id:uuid! answered_at:ts! grade:int? voice_answer_text:text? created_at:ts!",
 "syntheses": "id:uuid! space_id:uuid? user_id:uuid! topic:text? points:json! disagreements:json! suggested_action:text? source_save_ids:uuid[]! created_at:ts!",
 "reminders": "id:uuid! save_id:uuid user_id:uuid! kind:reminder_kind fire_at:ts? geofence:json? fired:bool! created_at:ts!",
 "jobs": "id:uuid! save_id:uuid? space_id:uuid? user_id:uuid! type:job_type state:job_state! attempts:int! error:text? locked_at:ts? run_after:ts! payload:json! created_at:ts! updated_at:ts!",
 "exports": "id:uuid! space_id:uuid user_id:uuid! kind:export_kind options:json! file_path:text? share_slug:text? created_at:ts!",
 "usage": "id:uuid! user_id:uuid! save_id:uuid? kind:text input_tokens:int! output_tokens:int! audio_seconds:num! usd:num! created_at:ts!",
 "settings": "user_id:uuid! theme:theme_pref! accent:text! accent_custom:text? text_scale:num! density:int! reduce_motion:bool! haptics:bool! monthly_budget_usd:num! queue_time:text! queue_minutes:int! quiet_hours:json! created_at:ts! updated_at:ts!",
}
ENUMS = {
 "space_kind": ["topic", "project", "inbox"],
 "platform": ["instagram", "tiktok", "youtube", "web", "screenshot"],
 "save_status": ["queued", "processing", "ready", "failed", "dead_link"],
 "intent": ["learn", "try", "visit", "buy", "inspire", "fun"],
 "reminder_kind": ["time", "place", "context"],
 "job_type": ["ingest", "reprocess", "synthesize", "export"],
 "job_state": ["queued", "running", "done", "failed"],
 "export_kind": ["brief", "moodboard", "deck", "collection"],
 "theme_pref": ["system", "dark", "light", "black"],
}
BASE = {"uuid": "string", "text": "string", "date": "string", "ts": "string", "int": "number", "num": "number", "bool": "boolean", "json": "Json", "unknown": "unknown"}

def ts_type(t):
    arr = t.endswith("[]")
    t = t[:-2] if arr else t
    s = f'Database["stash"]["Enums"]["{t}"]' if t in ENUMS else BASE[t]
    return s + "[]" if arr else s

out = ["// Generated by scripts/gen-types.py — do not edit by hand.", "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];", "", "export type Database = {", '  __InternalSupabase: { PostgrestVersion: "14.5" };', "  stash: {", "    Tables: {"]
for table, spec in TABLES.items():
    cols = []
    for c in spec.split():
        name, t = c.split(":")
        default = t.endswith("!"); t = t.rstrip("!")
        null = t.endswith("?"); t = t.rstrip("?")
        cols.append((name, ts_type(t), null, default))
    out.append(f"      {table}: {{")
    for kind in ("Row", "Insert", "Update"):
        out.append(f"        {kind}: {{")
        for name, t, null, default in cols:
            if name == "tsv" and kind != "Row":
                continue
            ty = f"{t} | null" if null else t
            opt = "?" if kind == "Update" or (kind == "Insert" and (null or default)) else ""
            out.append(f"          {name}{opt}: {ty};")
        out.append("        };")
    out.append("        Relationships: [];")
    out.append("      };")
FUNCTIONS = [
  '      search_saves: { Args: { p_query: string; p_space_id?: string | null; p_embedding?: string | null; p_limit?: number }; Returns: { save_id: string; score: number; snippet: string | null; snippet_start: number | null }[] };',
  '      related_saves: { Args: { p_save_id: string; p_limit?: number }; Returns: { save_id: string; similarity: number }[] };',
  '      request_reprocess: { Args: { p_save_id: string }; Returns: undefined };',
]
out += ["    };", "    Views: { [_ in never]: never };", "    Functions: {", *FUNCTIONS, "    };", "    Enums: {"]
for e, vals in ENUMS.items():
    out.append(f"      {e}: " + " | ".join(f'"{v}"' for v in vals) + ";")
out += ["    };", "    CompositeTypes: { [_ in never]: never };", "  };", "};", "", 'export type Tables<T extends keyof Database["stash"]["Tables"]> = Database["stash"]["Tables"][T]["Row"];', 'export type Enums<T extends keyof Database["stash"]["Enums"]> = Database["stash"]["Enums"][T];', ""]
open("lib/supabase/types.ts", "w").write("\n".join(out))
print("wrote lib/supabase/types.ts")
