// Curated starter sources, by interest and language. Each URL is checked by
// lib/discover/health.ts; entries that stop working are hidden automatically.

export type SourceKind = "rss" | "youtube" | "newsletter";
export type Language = "en" | "fr";
/** Which channel Discover is showing: one kind of source, or everything. */
export type DiscoverKind = "all" | SourceKind;

/** True when a source of `kind` belongs in a Discover scoped to `scope`. */
export function inScope(scope: DiscoverKind, kind: SourceKind) {
  return scope === "all" || scope === kind;
}

export const CATALOG_CATEGORIES = [
  { id: "tech", name: "Tech & AI" },
  { id: "design", name: "Design & UX" },
  { id: "marketing", name: "Marketing" },
  { id: "business", name: "Business & Startups" },
  { id: "productivity", name: "Productivity" },
  { id: "creativity", name: "Creativity & Art" },
  { id: "science", name: "Science" },
  { id: "finance", name: "Finance & Economy" },
  { id: "news", name: "World News" },
  { id: "culture", name: "Culture & Ideas" },
  { id: "health", name: "Health & Fitness" },
  { id: "food", name: "Food & Cooking" },
  { id: "travel", name: "Travel" },
  { id: "gaming", name: "Gaming" },
  { id: "sports", name: "Sports" },
] as const;

export type CatalogCategoryId = (typeof CATALOG_CATEGORIES)[number]["id"];

export interface CatalogEntry {
  id: string;
  name: string;
  url: string;
  kind: SourceKind;
  lang: Language;
  category: CatalogCategoryId;
  description: string;
}

type Row = [name: string, url: string, kind: SourceKind, lang: Language, description: string];

const yt = (channelId: string) =>
  `https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`;
const handle = (name: string) => `https://www.youtube.com/@${name}`;

const ROWS: Record<CatalogCategoryId, Row[]> = {
  tech: [
    [
      "The Verge",
      "https://www.theverge.com/rss/index.xml",
      "rss",
      "en",
      "Technology, science and culture news",
    ],
    [
      "Ars Technica",
      "https://feeds.arstechnica.com/arstechnica/index",
      "rss",
      "en",
      "In-depth tech news and analysis",
    ],
    ["TechCrunch", "https://techcrunch.com/feed/", "rss", "en", "Startups and technology news"],
    ["Wired", "https://www.wired.com/feed/rss", "rss", "en", "How technology changes everything"],
    [
      "MIT Technology Review",
      "https://www.technologyreview.com/feed/",
      "rss",
      "en",
      "Emerging tech and AI, explained",
    ],
    ["Hacker News", "https://news.ycombinator.com/rss", "rss", "en", "Front page of Hacker News"],
    [
      "Numerama",
      "https://www.numerama.com/feed/",
      "rss",
      "fr",
      "Tech, sciences et culture numérique",
    ],
    [
      "Frandroid",
      "https://www.frandroid.com/feed",
      "rss",
      "fr",
      "Smartphones, high-tech et mobilité",
    ],
    ["Korben", "https://korben.info/feed", "rss", "fr", "Astuces, logiciels et culture geek"],
    ["Next", "https://next.ink/feed/", "rss", "fr", "Actualité numérique indépendante"],
    [
      "Marques Brownlee",
      yt("UCBJycsmduvYEL83R_U4JriQ"),
      "youtube",
      "en",
      "Clear, beautiful tech reviews",
    ],
    [
      "Fireship",
      yt("UCsBjURrPoezykLs9EqgamOA"),
      "youtube",
      "en",
      "Fast-paced coding and tech news",
    ],
    [
      "Two Minute Papers",
      yt("UCbfYPyITQ-7l4upoX8nvctg"),
      "youtube",
      "en",
      "AI research explained in minutes",
    ],
    [
      "Micode",
      yt("UCYnvxJ-PKiGXo_tYXpWAC-w"),
      "youtube",
      "fr",
      "Tech, hacking et enquêtes numériques",
    ],
    ["Underscore_", yt("UCWedHS9qKebauVIK2J7383g"), "youtube", "fr", "L'émission tech de Micode"],
    [
      "Stratechery",
      "https://stratechery.com/feed/",
      "newsletter",
      "en",
      "Ben Thompson on tech strategy",
    ],
    [
      "One Useful Thing",
      "https://www.oneusefulthing.org/feed",
      "newsletter",
      "en",
      "Ethan Mollick on using AI at work",
    ],
    [
      "The Pragmatic Engineer",
      "https://newsletter.pragmaticengineer.com/feed",
      "newsletter",
      "en",
      "Inside big tech and startups",
    ],
    [
      "Import AI",
      "https://importai.substack.com/feed",
      "newsletter",
      "en",
      "Weekly AI research digest",
    ],
    [
      "Linus Tech Tips",
      handle("LinusTechTips"),
      "youtube",
      "en",
      "PC hardware, gadgets and tech culture",
    ],
    [
      "ColdFusion",
      handle("ColdFusion"),
      "youtube",
      "en",
      "Documentaries on tech companies and ideas",
    ],
    [
      "Monsieur Bidouille",
      handle("MonsieurBidouille"),
      "youtube",
      "fr",
      "Vulgarisation tech et informatique",
    ],
    [
      "Platformer",
      "https://www.platformer.news/rss/",
      "newsletter",
      "en",
      "Casey Newton on big tech and democracy",
    ],
    [
      "Latent Space",
      "https://www.latent.space/feed",
      "newsletter",
      "en",
      "AI engineering, podcasts and essays",
    ],
    [
      "Benedict Evans",
      "https://www.ben-evans.com/benedictevans?format=rss",
      "newsletter",
      "en",
      "Tech strategy and what matters this week",
    ],
  ],
  design: [
    [
      "Smashing Magazine",
      "https://www.smashingmagazine.com/feed/",
      "rss",
      "en",
      "Web design and UX techniques",
    ],
    [
      "Nielsen Norman Group",
      "https://www.nngroup.com/feed/rss/",
      "rss",
      "en",
      "Evidence-based UX research",
    ],
    [
      "UX Collective",
      "https://uxdesign.cc/feed",
      "rss",
      "en",
      "Curated UX writing and case studies",
    ],
    [
      "A List Apart",
      "https://alistapart.com/main/feed/",
      "rss",
      "en",
      "Design, development and content",
    ],
    [
      "CSS-Tricks",
      "https://css-tricks.com/feed/",
      "rss",
      "en",
      "Front-end design and CSS techniques",
    ],
    [
      "Design Milk",
      "https://design-milk.com/feed/",
      "rss",
      "en",
      "Modern design, interiors and objects",
    ],
    [
      "Designboom",
      "https://www.designboom.com/feed/",
      "rss",
      "en",
      "Architecture, design and art news",
    ],
    [
      "Graphéine",
      "https://www.grapheine.com/feed",
      "rss",
      "fr",
      "Identité visuelle et culture graphique",
    ],
    [
      "Alsacréations",
      "https://www.alsacreations.com/rss/actualites.xml",
      "rss",
      "fr",
      "Web design et intégration",
    ],
    ["The Futur", handle("thefutur"), "youtube", "en", "Design business and branding"],
    ["DesignCourse", handle("DesignCourse"), "youtube", "en", "UI/UX design tutorials"],
    ["Flux Academy", handle("FluxAcademy"), "youtube", "en", "Web design and freelancing"],
    ["Grafikart", handle("grafikart"), "youtube", "fr", "Tutoriels web design et développement"],
    [
      "Sidebar",
      "https://sidebar.io/feed.xml",
      "newsletter",
      "en",
      "The five best design links, daily",
    ],
    [
      "UX Design Weekly",
      "https://uxdesignweekly.com/feed/",
      "newsletter",
      "en",
      "Weekly UX links and tools",
    ],
    ["Juxtopposed", handle("juxtopposed"), "youtube", "en", "Web design, UI and creative coding"],
    ["Figma", handle("Figma"), "youtube", "en", "Design talks, tutorials and Config sessions"],
  ],
  marketing: [
    ["Seth Godin", "https://seths.blog/feed/", "rss", "en", "Daily ideas on marketing and change"],
    [
      "HubSpot Marketing",
      "https://blog.hubspot.com/marketing/rss.xml",
      "rss",
      "en",
      "Inbound, content and social tactics",
    ],
    ["Moz Blog", "https://moz.com/blog/feed", "rss", "en", "SEO strategy and research"],
    [
      "Search Engine Journal",
      "https://www.searchenginejournal.com/feed/",
      "rss",
      "en",
      "SEO, PPC and content marketing",
    ],
    [
      "Social Media Today",
      "https://www.socialmediatoday.com/feeds/news/",
      "rss",
      "en",
      "Social platform news and trends",
    ],
    [
      "Blog du Modérateur",
      "https://www.blogdumoderateur.com/feed/",
      "rss",
      "fr",
      "Web, réseaux sociaux et marketing",
    ],
    [
      "Webmarketing & co'm",
      "https://www.webmarketing-com.com/feed",
      "rss",
      "fr",
      "Marketing digital et growth",
    ],
    ["Abondance", "https://www.abondance.com/feed", "rss", "fr", "Référencement et SEO"],
    [
      "Journal du CM",
      "https://www.journalducm.com/feed/",
      "rss",
      "fr",
      "Community management et social media",
    ],
    ["Siècle Digital", "https://siecledigital.fr/feed/", "rss", "fr", "Marketing, tech et médias"],
    ["Neil Patel", handle("neilpatel"), "youtube", "en", "SEO and digital marketing tips"],
    ["Ahrefs", handle("AhrefsCom"), "youtube", "en", "SEO and content marketing tutorials"],
    ["HubSpot Marketing", handle("HubSpotMarketing"), "youtube", "en", "Marketing strategy videos"],
    ["Yomi Denzel", handle("YomiDenzel"), "youtube", "fr", "E-commerce et marketing en ligne"],
    [
      "Growth Memo",
      "https://www.growth-memo.com/feed",
      "newsletter",
      "en",
      "Kevin Indig on SEO and growth",
    ],
    [
      "Lenny's Newsletter",
      "https://www.lennysnewsletter.com/feed",
      "newsletter",
      "en",
      "Product, growth and careers",
    ],
    ["GaryVee", handle("garyvee"), "youtube", "en", "Marketing, social media and entrepreneurship"],
    ["Semrush", handle("semrush"), "youtube", "en", "SEO and content marketing, explained"],
  ],
  business: [
    [
      "Fast Company",
      "https://www.fastcompany.com/latest/rss",
      "rss",
      "en",
      "Innovation, leadership and design",
    ],
    ["Fortune", "https://fortune.com/feed/", "rss", "en", "Business and markets news"],
    [
      "Paul Graham Essays",
      "http://www.aaronsw.com/2002/feeds/pgessays.rss",
      "rss",
      "en",
      "Classic essays on startups",
    ],
    [
      "Entrepreneur",
      "https://www.entrepreneur.com/latest.rss",
      "rss",
      "en",
      "Advice for founders and small business",
    ],
    [
      "Maddyness",
      "https://www.maddyness.com/feed/",
      "rss",
      "fr",
      "Startups et innovation en France",
    ],
    ["FrenchWeb", "https://www.frenchweb.fr/feed", "rss", "fr", "Écosystème tech et startups"],
    [
      "Journal du Net",
      "https://www.journaldunet.com/rss/",
      "rss",
      "fr",
      "Économie numérique et business",
    ],
    [
      "Challenges",
      "https://www.challenges.fr/rss.xml",
      "rss",
      "fr",
      "Économie, entreprises et patrons",
    ],
    ["Y Combinator", yt("UCcefcZRL2oaA_uBNeo5UOWg"), "youtube", "en", "Startup advice from YC"],
    ["Alex Hormozi", handle("AlexHormozi"), "youtube", "en", "Growing and scaling a business"],
    ["Stanford GSB", handle("stanfordgsb"), "youtube", "en", "Talks from Stanford business school"],
    [
      "Olivier Roland",
      handle("OlivierRoland"),
      "youtube",
      "fr",
      "Entrepreneuriat et liberté financière",
    ],
    [
      "Not Boring",
      "https://www.notboring.co/feed",
      "newsletter",
      "en",
      "Packy McCormick on business strategy",
    ],
    [
      "The Generalist",
      "https://www.generalist.com/feed",
      "newsletter",
      "en",
      "Deep dives on companies and founders",
    ],
    [
      "Lenny's Newsletter",
      "https://www.lennysnewsletter.com/feed",
      "newsletter",
      "en",
      "Product, growth and careers",
    ],
    [
      "My First Million",
      handle("MyFirstMillionPod"),
      "youtube",
      "en",
      "Business ideas and founder stories",
    ],
  ],
  productivity: [
    ["Farnam Street", "https://fs.blog/feed/", "rss", "en", "Mental models and better thinking"],
    [
      "Cal Newport",
      "https://calnewport.com/feed/",
      "rss",
      "en",
      "Deep work and digital minimalism",
    ],
    [
      "James Clear",
      "https://jamesclear.com/feed",
      "rss",
      "en",
      "Habits and continuous improvement",
    ],
    ["Ness Labs", "https://nesslabs.com/feed", "rss", "en", "Mindful productivity and learning"],
    ["Lifehacker", "https://lifehacker.com/feed/rss", "rss", "en", "Tips to do everything better"],
    [
      "Des livres pour changer de vie",
      "https://www.des-livres-pour-changer-de-vie.com/feed/",
      "rss",
      "fr",
      "Développement personnel par les livres",
    ],
    [
      "Habitudes Zen",
      "https://habitudes-zen.net/feed/",
      "rss",
      "fr",
      "Simplicité et bonnes habitudes",
    ],
    ["Ali Abdaal", yt("UCoOae5nYA7VqaXzerajD0lg"), "youtube", "en", "Evidence-based productivity"],
    ["Thomas Frank", handle("Thomasfrank"), "youtube", "en", "Study and productivity systems"],
    ["Matt D'Avella", handle("mattdavella"), "youtube", "en", "Minimalism and habits"],
    [
      "Forte Labs",
      "https://fortelabs.com/feed/",
      "newsletter",
      "en",
      "Tiago Forte on building a second brain",
    ],
    [
      "Cal Newport (YouTube)",
      handle("calnewportmedia"),
      "youtube",
      "en",
      "Deep Questions: focus and meaningful work",
    ],
  ],
  creativity: [
    [
      "Colossal",
      "https://www.thisiscolossal.com/feed/",
      "rss",
      "en",
      "Art, craft and visual culture",
    ],
    [
      "The Marginalian",
      "https://www.themarginalian.org/feed/",
      "rss",
      "en",
      "Maria Popova on art, science and life",
    ],
    ["Austin Kleon", "https://austinkleon.com/feed/", "rss", "en", "Creativity in a digital age"],
    ["Hyperallergic", "https://hyperallergic.com/feed/", "rss", "en", "Art news and criticism"],
    [
      "Creative Boom",
      "https://www.creativeboom.com/feed/",
      "rss",
      "en",
      "Inspiration for creative people",
    ],
    ["PetaPixel", "https://petapixel.com/feed/", "rss", "en", "Photography news and techniques"],
    [
      "Booooooom",
      "https://www.booooooom.com/feed/",
      "rss",
      "en",
      "Contemporary art and illustration",
    ],
    ["Fubiz", "https://www.fubiz.net/feed/", "rss", "fr", "Art, design et créativité"],
    [
      "Beaux Arts Magazine",
      "https://www.beauxarts.com/feed/",
      "rss",
      "fr",
      "Actualité de l'art et des expositions",
    ],
    ["Phototrend", "https://phototrend.fr/feed/", "rss", "fr", "Photographie et techniques"],
    ["Proko", handle("ProkoTV"), "youtube", "en", "Drawing and anatomy lessons"],
    ["Peter McKinnon", handle("PeterMcKinnon"), "youtube", "en", "Photography and filmmaking"],
    ["Nerdwriter1", handle("Nerdwriter1"), "youtube", "en", "Video essays on art and film"],
    [
      "The Creative Independent",
      "https://thecreativeindependent.com/feed.xml",
      "newsletter",
      "en",
      "Artists on their creative practice",
    ],
  ],
  science: [
    [
      "Quanta Magazine",
      "https://www.quantamagazine.org/feed/",
      "rss",
      "en",
      "Math, physics and biology explained",
    ],
    [
      "ScienceDaily",
      "https://www.sciencedaily.com/rss/all.xml",
      "rss",
      "en",
      "Latest research news",
    ],
    [
      "New Scientist",
      "https://www.newscientist.com/feed/home/",
      "rss",
      "en",
      "Science and technology news",
    ],
    [
      "Nature",
      "https://www.nature.com/nature.rss",
      "rss",
      "en",
      "Research from the journal Nature",
    ],
    ["Nautilus", "https://nautil.us/feed/", "rss", "en", "Science connected to culture"],
    [
      "Futura Sciences",
      "https://www.futura-sciences.com/rss/actualites.xml",
      "rss",
      "fr",
      "Actualités scientifiques",
    ],
    [
      "Sciences et Avenir",
      "https://www.sciencesetavenir.fr/rss.xml",
      "rss",
      "fr",
      "Sciences, santé et nature",
    ],
    [
      "The Conversation France",
      "https://theconversation.com/fr/articles.atom",
      "rss",
      "fr",
      "Des chercheurs expliquent l'actualité",
    ],
    [
      "Le Monde – Sciences",
      "https://www.lemonde.fr/sciences/rss_full.xml",
      "rss",
      "fr",
      "La rubrique sciences du Monde",
    ],
    [
      "Veritasium",
      yt("UCHnyfMqiRRG1u-2MsSQLbXA"),
      "youtube",
      "en",
      "Science and engineering stories",
    ],
    ["Kurzgesagt", yt("UCsXVk37bltHxD1rDPwtNM8Q"), "youtube", "en", "Animated science explainers"],
    ["3Blue1Brown", yt("UCYO_jab_esuFRV4b17AJtAw"), "youtube", "en", "Math, visually explained"],
    [
      "SmarterEveryDay",
      yt("UC6107grRI4m0o2-emgoDnAA"),
      "youtube",
      "en",
      "Curiosity-driven experiments",
    ],
    [
      "ScienceEtonnante",
      handle("ScienceEtonnante"),
      "youtube",
      "fr",
      "Physique et sciences vulgarisées",
    ],
    ["Dr Nozman", handle("DrNozman"), "youtube", "fr", "Sciences et expériences"],
    [
      "Astral Codex Ten",
      "https://www.astralcodexten.com/feed",
      "newsletter",
      "en",
      "Scott Alexander on science and ideas",
    ],
    [
      "PBS Space Time",
      handle("pbsspacetime"),
      "youtube",
      "en",
      "Astrophysics and physics in depth",
    ],
    ["MinutePhysics", handle("minutephysics"), "youtube", "en", "Physics explained in minutes"],
    ["Astronogeek", handle("Astronogeek"), "youtube", "fr", "Astronomie et espace, avec humour"],
    [
      "The Intrinsic Perspective",
      "https://www.theintrinsicperspective.com/feed",
      "newsletter",
      "en",
      "Erik Hoel on science, mind and culture",
    ],
  ],
  finance: [
    [
      "A Wealth of Common Sense",
      "https://awealthofcommonsense.com/feed/",
      "rss",
      "en",
      "Ben Carlson on markets and investing",
    ],
    [
      "Marginal Revolution",
      "https://marginalrevolution.com/feed",
      "rss",
      "en",
      "Economics blog by Cowen and Tabarrok",
    ],
    [
      "Abnormal Returns",
      "https://abnormalreturns.com/feed/",
      "rss",
      "en",
      "Daily curated investing links",
    ],
    [
      "Mr. Money Mustache",
      "https://www.mrmoneymustache.com/feed/",
      "rss",
      "en",
      "Frugality and financial freedom",
    ],
    ["The Big Picture", "https://ritholtz.com/feed/", "rss", "en", "Barry Ritholtz on markets"],
    [
      "Le Monde – Économie",
      "https://www.lemonde.fr/economie/rss_full.xml",
      "rss",
      "fr",
      "Économie, entreprises et marchés",
    ],
    ["Journal du Coin", "https://journalducoin.com/feed/", "rss", "fr", "Crypto et blockchain"],
    ["The Plain Bagel", handle("ThePlainBagel"), "youtube", "en", "Investing explained simply"],
    ["Ben Felix", handle("BenFelixCSI"), "youtube", "en", "Evidence-based investing"],
    ["Patrick Boyle", handle("PBoyle"), "youtube", "en", "Finance and markets with wit"],
    ["Heu?reka", handle("Heureka"), "youtube", "fr", "Économie et finance expliquées"],
    [
      "Net Interest",
      "https://www.netinterest.co/feed",
      "newsletter",
      "en",
      "Marc Rubinstein on financial services",
    ],
    [
      "Kyla Scanlon",
      "https://kyla.substack.com/feed",
      "newsletter",
      "en",
      "Markets and the economy, made human",
    ],
    [
      "Apricitas Economics",
      "https://www.apricitas.io/feed",
      "newsletter",
      "en",
      "Data-driven macroeconomics",
    ],
    [
      "Noahpinion",
      "https://www.noahpinion.blog/feed",
      "newsletter",
      "en",
      "Economics and the world, by Noah Smith",
    ],
  ],
  news: [
    [
      "BBC News – World",
      "https://feeds.bbci.co.uk/news/world/rss.xml",
      "rss",
      "en",
      "Global news from the BBC",
    ],
    [
      "The Guardian – World",
      "https://www.theguardian.com/world/rss",
      "rss",
      "en",
      "World news from The Guardian",
    ],
    ["NPR News", "https://feeds.npr.org/1001/rss.xml", "rss", "en", "Top stories from NPR"],
    [
      "Al Jazeera",
      "https://www.aljazeera.com/xml/rss/all.xml",
      "rss",
      "en",
      "International news and analysis",
    ],
    [
      "The New York Times – World",
      "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
      "rss",
      "en",
      "World coverage from the NYT",
    ],
    ["DW News", "https://rss.dw.com/rdf/rss-en-all", "rss", "en", "Deutsche Welle in English"],
    ["Le Monde", "https://www.lemonde.fr/rss/une.xml", "rss", "fr", "À la une du Monde"],
    ["France 24", "https://www.france24.com/fr/rss", "rss", "fr", "L'actualité internationale"],
    [
      "Franceinfo",
      "https://www.francetvinfo.fr/titres.rss",
      "rss",
      "fr",
      "Toute l'actualité en continu",
    ],
    ["RFI", "https://www.rfi.fr/fr/rss", "rss", "fr", "Radio France Internationale"],
    [
      "Le Figaro",
      "https://www.lefigaro.fr/rss/figaro_actualites.xml",
      "rss",
      "fr",
      "Actualités du Figaro",
    ],
    [
      "Courrier international",
      "https://www.courrierinternational.com/feed/all/rss.xml",
      "rss",
      "fr",
      "La presse mondiale en français",
    ],
    ["Vox", yt("UCLXo7UDZvByw2ixzpQCufnA"), "youtube", "en", "Explainers on news and culture"],
    ["Johnny Harris", handle("johnnyharris"), "youtube", "en", "Geopolitics and maps, explained"],
    [
      "TLDR News Global",
      handle("TLDRnewsGLOBAL"),
      "youtube",
      "en",
      "Global news, briefly explained",
    ],
    [
      "HugoDécrypte",
      yt("UCAcAnMF0OrCtUep3Y4M-ZPw"),
      "youtube",
      "fr",
      "L'actualité décryptée pour tous",
    ],
    [
      "Letters from an American",
      "https://heathercoxrichardson.substack.com/feed",
      "newsletter",
      "en",
      "Heather Cox Richardson on US politics",
    ],
    ["Le Monde (YouTube)", handle("lemondefr"), "youtube", "fr", "Décryptages vidéo du Monde"],
    ["FRANCE 24", handle("FRANCE24"), "youtube", "fr", "L'actualité internationale en vidéo"],
    ["FRANCE 24 English", handle("France24_en"), "youtube", "en", "International news and reports"],
  ],
  culture: [
    [
      "The Atlantic",
      "https://www.theatlantic.com/feed/all/",
      "rss",
      "en",
      "Ideas, politics and culture",
    ],
    [
      "The New Yorker",
      "https://www.newyorker.com/feed/everything",
      "rss",
      "en",
      "Reporting, essays and fiction",
    ],
    ["Aeon", "https://aeon.co/feed.rss", "rss", "en", "Essays on philosophy, science and art"],
    ["Kottke", "https://feeds.kottke.org/main", "rss", "en", "Liberal arts web log since 1998"],
    [
      "Open Culture",
      "https://www.openculture.com/feed",
      "rss",
      "en",
      "Free cultural and educational media",
    ],
    ["Longreads", "https://longreads.com/feed/", "rss", "en", "The best long-form storytelling"],
    [
      "Le Monde – Culture",
      "https://www.lemonde.fr/culture/rss_full.xml",
      "rss",
      "fr",
      "Cinéma, livres, musique et arts",
    ],
    ["Les Inrocks", "https://www.lesinrocks.com/feed/", "rss", "fr", "Musique, cinéma et société"],
    ["Konbini", "https://www.konbini.com/fr/feed/", "rss", "fr", "Pop culture et société"],
    ["Slate.fr", "https://www.slate.fr/rss.xml", "rss", "fr", "Analyses et idées"],
    [
      "The School of Life",
      handle("theschooloflifetv"),
      "youtube",
      "en",
      "Philosophy for everyday life",
    ],
    [
      "Lessons from the Screenplay",
      handle("LessonsfromtheScreenplay"),
      "youtube",
      "en",
      "How great films are written",
    ],
    ["Nota Bene", handle("NotaBeneMovies"), "youtube", "fr", "L'histoire racontée simplement"],
    [
      "Culture Study",
      "https://annehelen.substack.com/feed",
      "newsletter",
      "en",
      "Anne Helen Petersen on how we live",
    ],
    [
      "The Honest Broker",
      "https://www.honest-broker.com/feed",
      "newsletter",
      "en",
      "Ted Gioia on music and culture",
    ],
    [
      "Philosophy Tube",
      handle("PhilosophyTube"),
      "youtube",
      "en",
      "Philosophy through theatre and essays",
    ],
    [
      "kaptainkristian",
      handle("kaptainkristian"),
      "youtube",
      "en",
      "Video essays on animation and film",
    ],
  ],
  health: [
    [
      "Stronger by Science",
      "https://www.strongerbyscience.com/feed/",
      "rss",
      "en",
      "Evidence-based strength training and nutrition",
    ],
    [
      "Nerd Fitness",
      "https://www.nerdfitness.com/feed/",
      "rss",
      "en",
      "Fitness for regular people",
    ],
    [
      "Mark's Daily Apple",
      "https://www.marksdailyapple.com/feed/",
      "rss",
      "en",
      "Health, food and movement",
    ],
    [
      "Runner's World",
      "https://www.runnersworld.com/rss/all.xml/",
      "rss",
      "en",
      "Running training, gear and races",
    ],
    [
      "ScienceDaily Health",
      "https://www.sciencedaily.com/rss/health_medicine.xml",
      "rss",
      "en",
      "The latest health and medicine research",
    ],
    [
      "Le Monde Santé",
      "https://www.lemonde.fr/sante/rss_full.xml",
      "rss",
      "fr",
      "L'actualité santé du Monde",
    ],
    [
      "Futura Santé",
      "https://www.futura-sciences.com/rss/sante/actualites.xml",
      "rss",
      "fr",
      "Actualités santé et médecine",
    ],
    ["Jeff Nippard", handle("JeffNippard"), "youtube", "en", "Science-based training and physique"],
    [
      "Huberman Lab",
      handle("hubermanlab"),
      "youtube",
      "en",
      "Neuroscience tools for health and performance",
    ],
    [
      "Yoga With Adriene",
      handle("yogawithadriene"),
      "youtube",
      "en",
      "Free yoga practices for every level",
    ],
    [
      "Renaissance Periodization",
      handle("RenaissancePeriodization"),
      "youtube",
      "en",
      "Hypertrophy training and diet",
    ],
    ["Tibo InShape", handle("TiboInShape"), "youtube", "fr", "Musculation, sport et défis"],
    [
      "Your Local Epidemiologist",
      "https://yourlocalepidemiologist.substack.com/feed",
      "newsletter",
      "en",
      "Public health science, translated",
    ],
  ],
  food: [
    [
      "Smitten Kitchen",
      "https://smittenkitchen.com/feed/",
      "rss",
      "en",
      "Fearless cooking from a tiny kitchen",
    ],
    [
      "Budget Bytes",
      "https://www.budgetbytes.com/feed/",
      "rss",
      "en",
      "Delicious recipes designed for small budgets",
    ],
    [
      "Minimalist Baker",
      "https://minimalistbaker.com/feed/",
      "rss",
      "en",
      "Simple recipes, 10 ingredients or less",
    ],
    [
      "Bon Appétit",
      "https://www.bonappetit.com/feed/rss",
      "rss",
      "en",
      "Recipes, cooking tips and food culture",
    ],
    ["Eater", "https://www.eater.com/rss/index.xml", "rss", "en", "Restaurants and food news"],
    [
      "Love and Lemons",
      "https://www.loveandlemons.com/feed/",
      "rss",
      "en",
      "Vegetarian recipes with seasonal produce",
    ],
    [
      "Le Monde Gastronomie",
      "https://www.lemonde.fr/gastronomie/rss_full.xml",
      "rss",
      "fr",
      "Recettes, chefs et tables",
    ],
    [
      "Amour de cuisine",
      "https://www.amourdecuisine.fr/feed",
      "rss",
      "fr",
      "Recettes du Maghreb et d'ailleurs",
    ],
    [
      "Joshua Weissman",
      handle("JoshuaWeissman"),
      "youtube",
      "en",
      "Making food better than takeout",
    ],
    ["Ethan Chlebowski", handle("EthanChlebowski"), "youtube", "en", "Cooking with intention"],
    ["Adam Ragusea", handle("aragusea"), "youtube", "en", "Home cooking and food science"],
    ["Hervé Cuisine", handle("HerveCuisine"), "youtube", "fr", "Recettes faciles en vidéo"],
    [
      "Alison Roman",
      "https://alisoneroman.substack.com/feed",
      "newsletter",
      "en",
      "Recipes and opinions from Alison Roman",
    ],
  ],
  travel: [
    [
      "Nomadic Matt",
      "https://www.nomadicmatt.com/feed/",
      "rss",
      "en",
      "Travel on a budget, smarter",
    ],
    [
      "Atlas Obscura",
      "https://www.atlasobscura.com/feeds/latest",
      "rss",
      "en",
      "The world's hidden wonders",
    ],
    [
      "Condé Nast Traveler",
      "https://www.cntraveler.com/feed/rss",
      "rss",
      "en",
      "Travel guides and inspiration",
    ],
    [
      "Adventurous Kate",
      "https://www.adventurouskate.com/feed/",
      "rss",
      "en",
      "Solo female travel",
    ],
    [
      "The Points Guy",
      "https://thepointsguy.com/feed/",
      "rss",
      "en",
      "Points, miles and travel deals",
    ],
    ["Skift", "https://skift.com/feed/", "rss", "en", "The business of travel"],
    ["Novo-Monde", "https://www.novo-monde.com/feed/", "rss", "fr", "Blog voyage et tour du monde"],
    [
      "Instinct Voyageur",
      "https://www.instinct-voyageur.fr/feed/",
      "rss",
      "fr",
      "Récits et conseils de voyage",
    ],
    ["Kara and Nate", handle("KaraandNate"), "youtube", "en", "Travel vlogs around the world"],
    ["Drew Binsky", handle("drewbinsky"), "youtube", "en", "Visiting every country in the world"],
    ["Mark Wiens", handle("MarkWiens"), "youtube", "en", "Food and travel adventures"],
    ["Bruno Maltor", handle("brunomaltor"), "youtube", "fr", "Voyages et découvertes"],
  ],
  gaming: [
    [
      "Polygon",
      "https://www.polygon.com/rss/index.xml",
      "rss",
      "en",
      "Games, culture and entertainment",
    ],
    [
      "Rock Paper Shotgun",
      "https://www.rockpapershotgun.com/feed",
      "rss",
      "en",
      "PC gaming news and reviews",
    ],
    ["Eurogamer", "https://www.eurogamer.net/feed", "rss", "en", "Video game news and reviews"],
    ["PC Gamer", "https://www.pcgamer.com/rss/", "rss", "en", "PC gaming news, reviews and guides"],
    ["Kotaku", "https://kotaku.com/rss", "rss", "en", "Gaming news and culture"],
    [
      "Game Developer",
      "https://www.gamedeveloper.com/rss.xml",
      "rss",
      "en",
      "The craft and business of making games",
    ],
    [
      "Gamekult",
      "https://www.gamekult.com/feed.xml",
      "rss",
      "fr",
      "Tests et actualité du jeu vidéo",
    ],
    [
      "Jeuxvideo.com",
      "https://www.jeuxvideo.com/rss/rss.xml",
      "rss",
      "fr",
      "Toute l'actualité du jeu vidéo",
    ],
    [
      "Journal du Geek",
      "https://www.journaldugeek.com/feed/",
      "rss",
      "fr",
      "Jeux vidéo, tech et pop culture",
    ],
    ["Game Maker's Toolkit", handle("GMTK"), "youtube", "en", "How game design works"],
    [
      "Digital Foundry",
      handle("DigitalFoundry"),
      "youtube",
      "en",
      "Game tech and performance analysis",
    ],
    ["Noclip", handle("NoclipDocs"), "youtube", "en", "Documentaries about video games"],
    [
      "Joueur du Grenier",
      handle("joueurdugrenier"),
      "youtube",
      "fr",
      "Tests de jeux rétro, avec humour",
    ],
  ],
  sports: [
    ["BBC Sport", "https://feeds.bbci.co.uk/sport/rss.xml", "rss", "en", "Sport news from the BBC"],
    [
      "BBC Football",
      "https://feeds.bbci.co.uk/sport/football/rss.xml",
      "rss",
      "en",
      "Football news and results",
    ],
    [
      "Guardian Football",
      "https://www.theguardian.com/football/rss",
      "rss",
      "en",
      "Football news, analysis and opinion",
    ],
    [
      "Sky Sports Football",
      "https://www.skysports.com/rss/12040",
      "rss",
      "en",
      "Premier League and football news",
    ],
    ["Autosport F1", "https://www.autosport.com/rss/f1/news/", "rss", "en", "Formula 1 news"],
    [
      "L'Équipe",
      "https://dwh.lequipe.fr/api/edito/rss?path=/",
      "rss",
      "fr",
      "L'actualité du sport",
    ],
    [
      "RMC Sport Football",
      "https://rmcsport.bfmtv.com/rss/football/",
      "rss",
      "fr",
      "Football : actu, mercato, résultats",
    ],
    [
      "Foot Mercato",
      "https://www.footmercato.net/flux-rss",
      "rss",
      "fr",
      "Mercato et actualité du football",
    ],
    ["Hespress Sport", "https://fr.hespress.com/sport/feed", "rss", "fr", "Le sport au Maroc"],
    ["Formula 1", handle("Formula1"), "youtube", "en", "Official F1 highlights"],
    ["NBA", handle("NBA"), "youtube", "en", "NBA highlights"],
  ],
};

function slug(text: string) {
  return text
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export const CATALOG: CatalogEntry[] = CATALOG_CATEGORIES.flatMap(({ id: category }) =>
  ROWS[category].map(([name, url, kind, lang, description]) => ({
    id: `${category}-${slug(name)}-${kind}`,
    name,
    url,
    kind,
    lang,
    category,
    description,
  }))
);

export function categoryName(id: CatalogCategoryId) {
  return CATALOG_CATEGORIES.find((c) => c.id === id)?.name ?? id;
}
