import type { Language } from "@/lib/discover/catalog";
import { topicFeedUrl } from "@/lib/discover/topics";
import type { DeskId } from "@/lib/news/desks";

// Curated news sources for the News tab, checked from Vercel's network.
// Outlets that block feed readers (Médias24, Le360, Le Matin, Morocco World
// News) come through Bing News search of their site instead.

export interface NewsSource {
  id: string;
  name: string;
  url: string;
  lang: Language;
  desk: DeskId;
  region?: "ma";
  description: string;
  /** Pre-checked in the first-run setup. */
  pick?: boolean;
}

const site = (host: string, lang: Language) => topicFeedUrl(`site:${host}`, lang);

export const NEWS_SOURCES: NewsSource[] = [
  // Maroc
  {
    id: "hespress-fr",
    name: "Hespress FR",
    url: "https://fr.hespress.com/feed",
    lang: "fr",
    desk: "morocco",
    region: "ma",
    description: "L'actualité marocaine en continu",
    pick: true,
  },
  {
    id: "le360",
    name: "Le360",
    url: site("le360.ma", "fr"),
    lang: "fr",
    desk: "morocco",
    region: "ma",
    description: "Info Maroc, via la recherche d'actualités",
    pick: true,
  },
  {
    id: "medias24",
    name: "Médias24",
    url: site("medias24.com", "fr"),
    lang: "fr",
    desk: "morocco",
    region: "ma",
    description: "Économie et société au Maroc, via la recherche d'actualités",
    pick: true,
  },
  {
    id: "hespress-en",
    name: "Hespress English",
    url: "https://en.hespress.com/feed",
    lang: "en",
    desk: "morocco",
    region: "ma",
    description: "Moroccan news in English",
    pick: true,
  },
  {
    id: "morocco-world-news",
    name: "Morocco World News",
    url: site("moroccoworldnews.com", "en"),
    lang: "en",
    desk: "morocco",
    region: "ma",
    description: "Morocco's English-language daily, via news search",
  },
  {
    id: "telquel",
    name: "TelQuel",
    url: "https://telquel.ma/feed",
    lang: "fr",
    desk: "morocco",
    region: "ma",
    description: "Magazine d'actualité et d'enquêtes",
  },
  {
    id: "le-matin",
    name: "Le Matin",
    url: site("lematin.ma", "fr"),
    lang: "fr",
    desk: "morocco",
    region: "ma",
    description: "Quotidien marocain, via la recherche d'actualités",
  },
  {
    id: "le-desk",
    name: "Le Desk",
    url: "https://ledesk.ma/feed/",
    lang: "fr",
    desk: "morocco",
    region: "ma",
    description: "Journalisme d'investigation (articles souvent réservés aux abonnés)",
  },
  {
    id: "lesiteinfo",
    name: "Le Site Info",
    url: "https://www.lesiteinfo.com/feed/",
    lang: "fr",
    desk: "morocco",
    region: "ma",
    description: "Actualités du Maroc",
  },
  {
    id: "aujourdhui",
    name: "Aujourd'hui le Maroc",
    url: "https://aujourdhui.ma/feed",
    lang: "fr",
    desk: "morocco",
    region: "ma",
    description: "Quotidien généraliste",
  },
  {
    id: "north-africa-post",
    name: "The North Africa Post",
    url: "https://northafricapost.com/feed",
    lang: "en",
    desk: "morocco",
    region: "ma",
    description: "Morocco and the Maghreb in English",
  },

  // Monde
  {
    id: "bbc-world",
    name: "BBC News World",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    lang: "en",
    desk: "world",
    description: "World news from the BBC",
    pick: true,
  },
  {
    id: "france24-fr",
    name: "France 24",
    url: "https://www.france24.com/fr/rss",
    lang: "fr",
    desk: "world",
    description: "L'actualité internationale",
    pick: true,
  },
  {
    id: "lemonde-international",
    name: "Le Monde International",
    url: "https://www.lemonde.fr/international/rss_full.xml",
    lang: "fr",
    desk: "world",
    description: "L'international du Monde",
    pick: true,
  },
  {
    id: "guardian-world",
    name: "The Guardian World",
    url: "https://www.theguardian.com/world/rss",
    lang: "en",
    desk: "world",
    description: "World news and analysis",
  },
  {
    id: "aljazeera",
    name: "Al Jazeera",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    lang: "en",
    desk: "world",
    description: "Global news with a focus on the Global South",
  },
  {
    id: "france24-en",
    name: "France 24 English",
    url: "https://www.france24.com/en/rss",
    lang: "en",
    desk: "world",
    description: "International news in English",
  },
  {
    id: "rfi",
    name: "RFI",
    url: "https://www.rfi.fr/fr/rss",
    lang: "fr",
    desk: "world",
    description: "Radio France Internationale",
  },
  {
    id: "courrier-international",
    name: "Courrier international",
    url: "https://www.courrierinternational.com/feed/all/rss.xml",
    lang: "fr",
    desk: "world",
    description: "Le meilleur de la presse étrangère",
  },
  {
    id: "nyt-world",
    name: "The New York Times World",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    lang: "en",
    desk: "world",
    description: "World coverage from the Times",
  },
  {
    id: "npr-world",
    name: "NPR World",
    url: "https://feeds.npr.org/1004/rss.xml",
    lang: "en",
    desk: "world",
    description: "World news from NPR",
  },
  {
    id: "figaro-international",
    name: "Le Figaro International",
    url: "https://www.lefigaro.fr/rss/figaro_international.xml",
    lang: "fr",
    desk: "world",
    description: "L'international du Figaro",
  },
  {
    id: "dw",
    name: "DW",
    url: "https://rss.dw.com/rdf/rss-en-all",
    lang: "en",
    desk: "world",
    description: "Deutsche Welle, Germany's international broadcaster",
  },

  // Europe
  {
    id: "euronews-fr",
    name: "Euronews",
    url: "https://fr.euronews.com/rss",
    lang: "fr",
    desk: "europe",
    description: "L'actualité européenne",
    pick: true,
  },
  {
    id: "politico-europe",
    name: "Politico Europe",
    url: "https://www.politico.eu/feed/",
    lang: "en",
    desk: "europe",
    description: "EU politics and policy",
    pick: true,
  },
  {
    id: "lemonde-europe",
    name: "Le Monde Europe",
    url: "https://www.lemonde.fr/europe/rss_full.xml",
    lang: "fr",
    desk: "europe",
    description: "L'Europe vue par Le Monde",
  },
  {
    id: "euronews-en",
    name: "Euronews English",
    url: "https://www.euronews.com/rss",
    lang: "en",
    desk: "europe",
    description: "European news in English",
  },
  {
    id: "guardian-europe",
    name: "The Guardian Europe",
    url: "https://www.theguardian.com/world/europe-news/rss",
    lang: "en",
    desk: "europe",
    description: "European news and analysis",
  },
  {
    id: "bbc-europe",
    name: "BBC News Europe",
    url: "https://feeds.bbci.co.uk/news/world/europe/rss.xml",
    lang: "en",
    desk: "europe",
    description: "European news from the BBC",
  },
  {
    id: "franceinfo",
    name: "franceinfo",
    url: "https://www.francetvinfo.fr/titres.rss",
    lang: "fr",
    desk: "europe",
    description: "Les titres de franceinfo",
  },

  // Afrique
  {
    id: "jeune-afrique",
    name: "Jeune Afrique",
    url: "https://www.jeuneafrique.com/feed/",
    lang: "fr",
    desk: "africa",
    description: "L'actualité africaine",
    pick: true,
  },
  {
    id: "rfi-afrique",
    name: "RFI Afrique",
    url: "https://www.rfi.fr/fr/afrique/rss",
    lang: "fr",
    desk: "africa",
    description: "L'Afrique sur RFI",
    pick: true,
  },
  {
    id: "africanews",
    name: "Africanews",
    url: "https://www.africanews.com/feed/rss",
    lang: "en",
    desk: "africa",
    description: "Pan-African news",
  },

  // Économie
  {
    id: "lemonde-economie",
    name: "Le Monde Économie",
    url: "https://www.lemonde.fr/economie/rss_full.xml",
    lang: "fr",
    desk: "economy",
    description: "L'économie du Monde",
    pick: true,
  },
  {
    id: "bbc-business",
    name: "BBC Business",
    url: "https://feeds.bbci.co.uk/news/business/rss.xml",
    lang: "en",
    desk: "economy",
    description: "Business news from the BBC",
    pick: true,
  },
  {
    id: "leseco",
    name: "LesEco.ma",
    url: "https://leseco.ma/feed/",
    lang: "fr",
    desk: "economy",
    region: "ma",
    description: "L'économie marocaine",
    pick: true,
  },
  {
    id: "challenge",
    name: "Challenge",
    url: "https://www.challenge.ma/feed/",
    lang: "fr",
    desk: "economy",
    region: "ma",
    description: "Business et finance au Maroc",
  },
  {
    id: "lavieeco",
    name: "La Vie éco",
    url: "https://www.lavieeco.com/feed/",
    lang: "fr",
    desk: "economy",
    region: "ma",
    description: "Hebdomadaire économique marocain",
  },
  {
    id: "guardian-business",
    name: "The Guardian Business",
    url: "https://www.theguardian.com/business/rss",
    lang: "en",
    desk: "economy",
    description: "Business, economics and markets",
  },
  {
    id: "cnbc",
    name: "CNBC",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    lang: "en",
    desk: "economy",
    description: "Markets and business headlines",
  },
  {
    id: "figaro-economie",
    name: "Le Figaro Économie",
    url: "https://www.lefigaro.fr/rss/figaro_economie.xml",
    lang: "fr",
    desk: "economy",
    description: "L'économie du Figaro",
  },
  {
    id: "bfm-economie",
    name: "BFM Économie",
    url: "https://www.bfmtv.com/rss/economie/",
    lang: "fr",
    desk: "economy",
    description: "L'actualité économique de BFM",
  },
  {
    id: "la-tribune",
    name: "La Tribune",
    url: "https://www.latribune.fr/rss/rubriques/actualite.html",
    lang: "fr",
    desk: "economy",
    description: "Économie et finance",
  },

  // Sport
  {
    id: "lequipe",
    name: "L'Équipe",
    url: "https://dwh.lequipe.fr/api/edito/rss?path=/",
    lang: "fr",
    desk: "sports",
    description: "L'actualité du sport",
    pick: true,
  },
  {
    id: "hespress-sport",
    name: "Hespress Sport",
    url: "https://fr.hespress.com/sport/feed",
    lang: "fr",
    desk: "sports",
    region: "ma",
    description: "Le sport au Maroc",
    pick: true,
  },
  {
    id: "bbc-football",
    name: "BBC Football",
    url: "https://feeds.bbci.co.uk/sport/football/rss.xml",
    lang: "en",
    desk: "sports",
    description: "Football news and results",
  },
  {
    id: "le360-sport",
    name: "Le360 Sport",
    url: site("sport.le360.ma", "fr"),
    lang: "fr",
    desk: "sports",
    region: "ma",
    description: "Botola et Lions de l'Atlas, via la recherche d'actualités",
  },
  {
    id: "rmc-football",
    name: "RMC Sport Football",
    url: "https://rmcsport.bfmtv.com/rss/football/",
    lang: "fr",
    desk: "sports",
    description: "Football : actu, mercato, résultats",
  },
  {
    id: "foot-mercato",
    name: "Foot Mercato",
    url: "https://www.footmercato.net/flux-rss",
    lang: "fr",
    desk: "sports",
    description: "Mercato et actualité du football",
  },
  {
    id: "guardian-football",
    name: "The Guardian Football",
    url: "https://www.theguardian.com/football/rss",
    lang: "en",
    desk: "sports",
    description: "Football news and opinion",
  },
  {
    id: "sky-football",
    name: "Sky Sports Football",
    url: "https://www.skysports.com/rss/12040",
    lang: "en",
    desk: "sports",
    description: "Premier League and more",
  },
  {
    id: "bbc-sport",
    name: "BBC Sport",
    url: "https://feeds.bbci.co.uk/sport/rss.xml",
    lang: "en",
    desk: "sports",
    description: "All sports from the BBC",
  },

  // Tech
  {
    id: "the-verge",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    lang: "en",
    desk: "tech",
    description: "Technology, science and culture",
    pick: true,
  },
  {
    id: "numerama",
    name: "Numerama",
    url: "https://www.numerama.com/feed/",
    lang: "fr",
    desk: "tech",
    description: "Tech, sciences et culture numérique",
    pick: true,
  },
  {
    id: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    lang: "en",
    desk: "tech",
    description: "Startups and technology",
  },
  {
    id: "01net",
    name: "01net",
    url: "https://www.01net.com/actualites/feed/",
    lang: "fr",
    desk: "tech",
    description: "Actualité high-tech",
  },
  {
    id: "les-numeriques",
    name: "Les Numériques",
    url: "https://www.lesnumeriques.com/rss.xml",
    lang: "fr",
    desk: "tech",
    description: "Tests et actualité tech",
  },
];
